### ISSUE TITLE
cpp parser: not parsing function type that returns const

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#19]
Hey team, your project is amazing. I noticed that the following c++ code:
```
static_assert(std::is_same_v<A, const int&(int)>);
```
does not parse, but this one does:
```
static_assert(std::is_same_v<A, int&(int)>);
```

**Comment by codinuum** [comment]
Thank you for reporting!
We will look into it.

**Comment by codinuum** [comment]
We have just fixed the parser in the develop branch.
Could you try it?

**Comment by petr-bauch** [comment]
Wow. Thank you so much for such a quick fix. Works as expected.
