### ISSUE TITLE
cpp parser: declaration at the end of function bodies

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#21]
Hello and thanks again for your amazing project.

I've noticed a strange AST for the following code:

```
struct Foo {
  Foo(int b) {}
};
void bar() {
  Foo f(1);
}
```

The declaration of `f` is split into `StatementMacro:Foo` and function-call `f(1)`. But if I add return statement after the declaration:

```
struct Foo {
  Foo(int b) {}
};
void bar() {
  Foo f(1);
  return;
}
```

The AST looks as expected.

**Comment by codinuum** [comment]
Thank you for reporting!
We have just fixed the cpp parser.

**Comment by petr-bauch** [comment]
And thank you for fixing it so fast.
