### ISSUE TITLE
Declaration as if-condition

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#28]
This is probably more of a feature-request:
```
int main() {
  if (A* a = get_A()) return 1;
  return 0;
}
```
Will translate the condition as assignment where lhs is a multiplicative-expression.
```
int main() {
  if (A a = get_A()) return 1;
  return 0;
}
```
Will translate as macro `A` applied to `a`.

I understand it's ambiguous without knowing what is a type but a similar code outside of an if-statement works as expected, e.g.
```
int main() {
  A* a = get_A();
  return 0;
}
```
Is it because the parser by default expects the condition to be an expression?

**Comment by codinuum** [comment]
No.
The parser tries to resolve such ambiguities based on a number of (context dependent) rules.
Identifying what `A` is in the above depends on the order of the rules.

**Comment by codinuum** [comment]
However, we found the following in the C++20 specification.

> If a condition can be syntactically resolved as either an expression or a declaration, it is interpreted as the latter.

We are thinking about adding some rules.

**Comment by codinuum** [comment]
We have just modified the parser in [83ecfdd](https://github.com/codinuum/cca/commit/83ecfdd26ceb3240bb6c772e92f841a5c942f3cc).

**Comment by petr-bauch** [comment]
Sorry for the delay, just checked and it works perfectly.
