### ISSUE TITLE
[C++] final specifier is only reserved in some contexts

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#29]
So for example:
```
struct final final {};
```
is a legal definition.

https://en.cppreference.com/w/cpp/language/final

**Comment by codinuum** [comment]
Thank you for reporting!
We hope [ce3274d](https://github.com/codinuum/cca/commit/ce3274d0cf63b3640a336980944a70573038b205) works for you.

**Comment by codinuum** [comment]
Unfortunately, the parser failed to parse the local variable declaration.
We will look into it.

**Comment by codinuum** [comment]
Another commit ([f4926a7](https://github.com/codinuum/cca/commit/f4926a7c648f0edd5a5b7be18c7bb7576da31808)) remedies the problem.

**Comment by petr-bauch** [comment]
Very nice. It works in a lot of contexts now: arg name, param name, declared variable name.
One context which still does not seem to work is operator argument, e.g.
```
int f = 5 + final;
std::cerr << final;
```
Sorry to keep bothering you with this.

**Comment by codinuum** [comment]
[fb305e9](https://github.com/codinuum/cca/commit/fb305e9515e05dbe370dd76e4687f72ff39bcd2f) should fix that.

**Comment by petr-bauch** [comment]
Thank you so much for going over all those cases. Works now.
