### ISSUE TITLE
Opam packaging?

### ISSUE THREAD

**Issue by scemama** [codinuum/cca#3]
Hello,
some users are trying to make a Spack package for cca, and have some difficulties:
https://github.com/spack/spack/issues/18733

It would be very helpful if you could make an opam package for cca. We would then have the possibility to use [opam-bundle](https://github.com/scemama/opam-bundle) to create a .tar.gz file containing cca and all its dependencies, and its installation on a machine without OCaml would then be very easy. I know it requires a little bit of time to make an opam package, but it is very beneficial in the long term for sharing your code.

best,
Anthony

**Comment by codinuum** [comment]
Hi,

> It would be very helpful if you could make an opam package for cca. 

Thank you for your advice! We will think about that.

Best,
Codinuum

**Comment by codinuum** [comment]
We have just packaged CCA. Now you can install OCaml generated binaries of CCA via opam.

**Comment by scemama** [comment]
Thanks!
