### ISSUE TITLE
[C] Non-terminating parsing

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#31]
Hey Codinnuum team,

Your parser is amazing and this is the only issue in a while that we found.

With this file as input: https://git.yoctoproject.org/linux-yocto-contrib/plain/tools/testing/selftests/kvm/x86_64/pmu_event_filter_test.c

Cca does not produce any output (or terminate) for minutes. There is no memory consumption so I assume it's some recursion but we haven't found the problematic part of the code.

**Comment by codinuum** [comment]
Thank you for reporting!
We have fixed the non-termination bug in the develop branch.

**Comment by petr-bauch** [comment]
:heart: Yep it works for this file.

Could you please also have a look at this file: https://github.com/MidnightBSD/src/blob/master/sys/kern/kern_timeout.c

Similar problem but this time the parser produces this output (continuously):
```
[parsesrc.opt][WARNING][/home/petr/code/src/sys/kern/kern_timeout.c][969L,34C-33C(28290-28289)] unmatched parenthesis
```

**Comment by codinuum** [comment]
Hmm, the infinite loop begins at an odd preprocessor branch...
We've just fixed it. Does it work?

**Comment by petr-bauch** [comment]
Perfect. All works now.
Thank you so much.
