### ISSUE TITLE
[cpp] Parsing new-statement inside lambda can fail

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#33]
For example here:
```
int main() {
  int *ptr = nullptr;
  foo.bar([&ptr]() {
    ptr = new int;
  });
  return 1;
}
```
The assignment `ptr = new int;` fails. Maybe inside the context of a lambda (as argument) primitives types are not seen as types?

**Comment by codinuum** [comment]
The commit 10ce743 fixes the issue.

**Comment by petr-bauch** [comment]
Very nice. Thank you for the quick fix.
