### ISSUE TITLE
[cpp] 2 parsing issues

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#35]
Hey cca team, thank you for the amazing work.
We noticed that some syntax causes issues with parsing, specifically:
1)
```
struct left {} constexpr right{};
```
It seems that the parser does not expect `constexpr` in this declaration context.
2)
```
auto [a,b]{c()};
```
Directly calling the constructor of the structured binding instead of the more common assignment  operator, e.g. `auto [a,b] = c();`, causes parser error.

**Comment by codinuum** [comment]
The commit 488b49c contains fixes for both.

**Comment by petr-bauch** [comment]
Looks good.
