### ISSUE TITLE
[cpp] memory usage of deep pointer-to-pointer declaration

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#37]
The recursive processing of declaration like `X****..` seems to use large amount of memory (>10GB).

For example this clang test: https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGenCXX/mangle-extreme.cpp

**Comment by codinuum** [comment]
We have just pushed 790e490. It should parse the example with less memory footprint.

**Comment by petr-bauch** [comment]
Works nicely now.
