### ISSUE TITLE
[cpp] Regression in cpp parsing of marcros

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#38]
Hey team.
I noticed that recent changed introduced a small regression specifically
```
int main() {
  P *p = new P();
  foreach (QString arg, options->args)
    p->play(arg);
}
```
Crashes the parser with
```
PARSING ERROR: File "cpp_tree.ml", line 248, characters 22-28: Assertion failed
```
Somehow the fact that `p` was declared and then used in the macro confuses the hash table in the visitor.

**Comment by codinuum** [comment]
Thank you for reporting. We will look into it.

**Comment by codinuum** [comment]
We think we have fixed the issue.

**Comment by codinuum** [comment]
We have just fixed the regression.

**Comment by petr-bauch** [comment]
Perfect. Thank you.
